//
//  UIColor+AimStyleguide.swift
//
//  Generated by Zeplin on 7/18/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func projectBluishColor() -> UIColor {
		return UIColor(red: 42.0 / 255.0, green: 128.0 / 255.0, blue: 185.0 / 255.0, alpha: 1.0)
	}

	class func projectBlackColor() -> UIColor {
		return UIColor(white: 55.0 / 255.0, alpha: 1.0)
	}

	class func projectWhiteTwoColor() -> UIColor {
		return UIColor(white: 230.0 / 255.0, alpha: 1.0)
	}

    class func projectGrayColor() -> UIColor {
        return UIColor(white: 228.0 / 255.0, alpha: 1.0)
    }

	class func projectWhiteThreeColor() -> UIColor {
		return UIColor(white: 251.0 / 255.0, alpha: 1.0)
	}

	class func projectWhiteColor() -> UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class func projectWhiteFourColor() -> UIColor {
		return UIColor(white: 241.0 / 255.0, alpha: 1.0)
	}

	class func projectTomatoColor() -> UIColor {
		return UIColor(red: 218.0 / 255.0, green: 41.0 / 255.0, blue: 28.0 / 255.0, alpha: 1.0)
	}

	class func projectPinkishGreyColor() -> UIColor {
		return UIColor(white: 186.0 / 255.0, alpha: 1.0)
	}
    
   	class func projectSearchBarColor() -> UIColor {
        return UIColor(red: 160.0 / 255.0, green: 12.0 / 255.0, blue: 10.0 / 255.0, alpha: 1.0)
    }
}
